version: "2"

services:
  vote:
    image: alvarolazaro/examplevotingapp_vote:latest
    command: python app.py
    ports:
      - "5000:80"

  redis:
    image: redis:alpine
    ports: ["6379"]

  worker:
    image: alvarolazaro/examplevotingapp_worker:latest

  db:
    image: postgres:9.4

  result:
    image: alvarolazaro/examplevotingapp_result:latest
    command: nodemon --debug server.js
    ports:
      - "5001:80"
      - "5858:5858"
